### ISSUE TITLE
Not compatible with bootstrap 4.2.1 v

### ISSUE THREAD

**Issue by mrafea-sa** [hamidHeidarinia/bootstrap-rtl#2]
On 19 January 2019 ,this repository  is  not  Not compatible with bootstrap 4.2.1 version.
This repository  is missing a lot of code.
This  repository   needs  Ruby to be compiled

**Comment by hamidHeidarinia** [comment]
I know I'm going to miss a lot of codes.
And for compatibility with bootstrap version 4.2.1, please wait until the next few days the latest version of bootstrap rtl is ready.
