### ISSUE TITLE
Dropdown menu RTL Fix

### ISSUE THREAD

**Issue by pixieaka** [hamidHeidarinia/bootstrap-rtl#3]
Hey @hamidHeidarinia

Remove [ left:0 ] from [ .dropdown-menu ] class

And replace 

> .dropdown-menu-right{right:auto;left:0}.dropdown-menu-left{right:0;left:auto}

With 

> .dropdown-menu-right{right:0;left:auto}.dropdown-menu-left{right:auto;left:0}

And in bootstrap.js replace code in line number [ 1560 ]

>     BOTTOM: 'bottom-start',
>     BOTTOMEND: 'bottom-end',

With right RTL code

>     BOTTOM: 'bottom-end',
>     BOTTOMEND: 'bottom-start',

**Comment by hamidHeidarinia** [comment]
Hi @pixieaka
The reported changes were done.
Thank you for your report
